/*
  CS - READ TEXT FILES

  TODO: readColumn() can be simplified using getWord() from StringOperations.h
*/

//------------------------------------------------------------------------------------
//  countColumns
//
//  Count number of columns in a data file.
//  Does this by counting the number of words in the first line of the file
//
#include "ReadTextFiles.h"
int countColumns(char *file, int *Ncols)
{
  FILE *ifp;
  int  i, Nchar;
  char line[MAX_LINE_WIDTH], word[MAX_STR_L];

  // Open file
  if( (ifp = fopen(file, "r")) == NULL)
    {printf("\nERROR: Failed to open file \"%s\" in countLines()!\n\n", file); return(0);}

  // Read first line in the file
  fgets( line, sizeof line, ifp);

  // Read words in the line till end of line has been reached
  if( !countWords(line, word, &(*Ncols)) )
    {printf("\nERROR: Failed to execute countWords()!\n\n", file); return(0);}

  // Close file
  fclose(ifp);
  return(1);
}

// Count lines in a file
int countLines(char *file, int *Nlines)
{
  FILE *ifp;
  char line[MAX_LINE_WIDTH];

  if( (ifp = fopen(file, "r")) == NULL)
    {printf("\nERROR: Failed to open file \"%s\" in countLines()!\n\n", file);return(0);}

  (*Nlines) = 0;
  while( fgets( line, sizeof line, ifp) != NULL)
    (*Nlines)++;
  fclose(ifp);
  return(1);
}

//------------------------------------------------------------------------------------*/
//  checkFileName
//
//  Results are saved in a file named 'fileName'.
//  If this file already exists a new filename is generated by merging it with 
//  a string containing a number.
//
int checkFileName(char *fileName)
{
  int  exists,
       Nmax = 3,  // Length of 'str' by which the original string is modified
       N=0;
  char *newfileName,
       *fileNameTmp,
       *tmpc;
  FILE *ifp;

  newfileName=(char*)malloc(MAX_STR_L*sizeof(char));
  fileNameTmp=(char*)malloc(MAX_STR_L*sizeof(char));

  // If file already exists a new file name is tried
  if( (ifp = fopen( fileName , "r")) != NULL )
  {  
    fclose(ifp);
    exists=1;
    while(exists==1)
    {
      fileNameTmp[0]='\0';
      strcat(fileNameTmp, fileName);
      if(!fileNumber(fileNameTmp, N, Nmax, newfileName))
        {printf("ERROR: fileNumber() failed!\n"); return(0);}

      if( (ifp = fopen( newfileName , "r")) == NULL ) // File found!
        exists=0;
      N++;
    }
  }
  fileName[0]='\0';
  strcat(fileName, newfileName);

  return(1);
}




//--------------------------------------------------------------------------------
//  countFiles
//
//  Count number of files with the name fileName, or modified version of this
//  by the function 'fileNumber'. The numbers of these file names should be
//  sequencing.
//
int countFiles(char *fileName, int Nmax, int *Nfiles)
{
  int   i,
        check;
  char  c,
        ctmp[MAX_STR_L];
  FILE  *ifp;

  (*Nfiles)=0;
  if( (ifp=fopen(fileName, "r")) != 0)
  {
    (*Nfiles)++;
    fclose(ifp);
  }

  check=1;i=0;
  while(check)
  {
    if(!fileNumber(fileName, i, Nmax, ctmp))
    {
      printf("ERROR: fileNumber function not executed!\n");
      return(0);
    }
    if( (ifp=fopen(ctmp, "r")) != NULL) // file exists
    {
      (*Nfiles)++;
      fclose(ifp);
    }
    else  // file does not exist
      check=0;
    i++;
  }
  (*Nfiles)--;
  return(1);
}


//=========================================================================================
//  readColumn - Charley Schaefer 2011 
//
//  In general a file with data consists of textdata, followed by white space and column of numerical data below headers (strings).
//  This function reads a column of numerical data and stores it in the array 'col'.
//
//  To do this, the number of datapoints (Nsites), the first line of numerical data (dataLine) and the column desired to be read (Ncol)
//  are needed as input.
//
int readColumn(char *file, int Ndata, int Nheader, int Ncol, double *col)
{
  int  i,j,countCol;
  char c;
  char line[MAX_LINE_WIDTH];
  FILE *ifp;

  if(Ncol<0)
  {
    printf("WARNING: algorithm starts reading data at Ncol=1!\n");
    return(0);
  }

  if((ifp = fopen(file, "r")) == NULL){printf("ERROR: Failed to open \'%s\' in readColumn!\n", file); return(0);}

  // Go to first line in file that contains data
  for(i=0; i<Nheader; i++)
    fgets(line, sizeof(line), ifp);

  // Get data from last column
  for(i=Nheader-1; i<Ndata+Nheader-1; i++) // sweep over all lines
  {
    fgets(line, sizeof(line), ifp);

    j=0;countCol=0;// initialise position in line
    // Skip white space before first column

    // Find position of first column in the line
    if((c=line[j])==' ') // Read line until space is found (column delimiter)
    {
      while( (c=line[j]) != '\0' & c != '\n' & c != ' ')
        j++;

      // Read line until end of space
      while( (c=line[j]) == ' ' & c != '\0' & c != '\n')
        j++;
    }

    // start reading columns
    while( countCol<Ncol & (c=line[j]) != '\0' & c != '\n' )
    {
      // Read line until space is found
      while( (c=line[j]) != '\0' & c != '\n' & c != ' ')
        j++;

      // Read line until end of space
      while( (c=line[j]) == ' ' & c != '\0' & c != '\n')
        j++;

      // If character after space is not the end of the line a column is found
      if( (c=line[j]) != ' ' & c != '\0' & c != '\n')
        countCol++;
    }
    col[i+1-Nheader] = atof(line+j); // Read column entry	
  }
  fclose(ifp);
  return(1);
}
	
int readColumn_int(
	char	*file,		// File name 				
	int 	Ngrid, 		// Number of datapoints 		
	int 	dataLine, 	// Line number with first data points
	int		Ncol,		// Column number			
	int	*col		// Output array in with column values	 
	) // End of function arguments
	{
		int	i,j,countCol;
		char	c;
		char	line[MAX_LINE_WIDTH];
		FILE	*ifp;

		if(Ncol<0)
		{
			printf("WARNING: algorithm starts reading data at Ncol=1!\n");
			return(0);
		}

		if((ifp = fopen(file, "r")) == NULL){printf("ERROR: Failed to open \'%s\' in readColumn!\n", file); return(0);}

	/* Go to first line with data */	
		for(i=0; i<dataLine; i++)
			fgets(line, sizeof(line), ifp);

	/* Get data from last column */
		for(i=dataLine-1; i<Ngrid+dataLine-1; i++){
			fgets(line, sizeof(line), ifp);
			j=0;countCol=0;

			// Skip white space before first column
			if((c=line[j])==' ')
			   {/* Read line until space is found */	
				while( (c=line[j]) != '\0' & c != '\n' & c != ' ')
					j++;

				/* Read line until end of space */		
				while( (c=line[j]) == ' ' & c != '\0' & c != '\n')
					j++;}
			
			// start reading columns
			while( countCol<Ncol & (c=line[j]) != '\0' & c != '\n' ){
		
				/* Read line until space is found */	
				while( (c=line[j]) != '\0' & c != '\n' & c != ' ')
					j++;

				/* Read line until end of space */		
				while( (c=line[j]) == ' ' & c != '\0' & c != '\n')
					j++;

				/* If character after space is not the end of the line a column is found */
				if( (c=line[j]) != ' ' & c != '\0' & c != '\n')
					countCol++;
				}
			col[i+1-dataLine] = atoi(line+j);	
			}
		fclose(ifp);
		return(1);
	}
	
//---------------------------------------------------------------------
/*
	readRow - Charley Schaefer 2016-10-18
	
	Read matrix from data file
*/
int readRow(char *file, int Nrow, double *row)
{
	int		i,j,ind, Nchar;
	char 	word[MAX_STR_L], line[MAX_LINE_WIDTH];
	FILE 	*ifp;
	
	if( (ifp = fopen(file, "r")) == NULL){
		printf("\nERROR: Failed to open file \"%s\" in countLines!\n\n", file);
		return(0);
		}
	// get to line at Nrow (Nrow=0) is the first line
	i=0;
	while( fgets( line, sizeof line, ifp) != NULL & i<Nrow)
		i++;
	
	ind=0;i=0;
	while( getWord( line+ind, word, &Nchar) )
	{
		ind+= Nchar;
		row[i] = atof(word);
		i++; // Count number of words
	}
	
	fclose(ifp);
	return(1);
}
int readRow_short(char *file, int Nrow, short *row, int *Nword)
{
	int		i,j,ind, Nchar;
	char 	word[MAX_STR_L], line[MAX_LINE_WIDTH];
	FILE 	*ifp;
	
	if( (ifp = fopen(file, "r")) == NULL){
		printf("\nERROR: Failed to open file \"%s\" in countLines!\n\n", file);
		return(0);
		}
	// get to line at Nrow (Nrow=0) is the first line
	i=0;
	while( fgets( line, sizeof line, ifp) != NULL & i<Nrow)
		i++;
	
	ind=0;(*Nword)=0;
	while( getWord( line+ind, word, &Nchar) )
	{
		ind+= Nchar;
		row[(*Nword)] = atof(word);
		(*Nword)++; // Count number of words
	}
	
	fclose(ifp);
	return(1);
}
int readRow_int(char *file, int Nrow, int *row, int *Nword)
{
	int		i,j,ind, Nchar;
	char 	word[MAX_STR_L], line[MAX_LINE_WIDTH];
	FILE 	*ifp;
	
	if( (ifp = fopen(file, "r")) == NULL){
		printf("\nERROR: Failed to open file \"%s\" in countLines!\n\n", file);
		return(0);
		}
	// get to line at Nrow (Nrow=0) is the first line
	i=0;
	while( fgets( line, sizeof line, ifp) != NULL & i<Nrow)
		i++;
	
	ind=0;(*Nword)=0;
	while( getWord( line+ind, word, &Nchar) )
	{
		ind+= Nchar;
		row[(*Nword)] = atoi(word);
		(*Nword)++; // Count number of words
	}
	
	fclose(ifp);
	return(1);
}

//=========================================================================================
/* 
	readLine - Charley Schaefer 2014/11/04

 	Get a line from text file
*/
int readLine(char *file, char *line, int Nline)
{
	int i;
	FILE *ifp;
	if(NULL==(ifp = fopen(file, "r")))
		{printf("ERROR: Failed to read file \'%s\'!\n", file); return(0);}
	for(i=0; i<Nline; i++)
		fgets(line, MAX_LINE_WIDTH*sizeof(char), ifp);
	fclose(ifp);
	return(1);
}




//---------------------------------------------------------------------
/*
	readMatrix - Charley Schaefer 2014-11-04
	
	Read matrix from data file
*/
int readMatrix(char *file, double **mat, int Nlines, int Ncols)
{
	int		i,j,ind, Nchar;
	char 	c, word[MAX_STR_L], line[MAX_LINE_WIDTH];
	FILE 	*ifp;
	
	if( (ifp = fopen(file, "r")) == NULL){
		printf("\nERROR: Failed to open file \"%s\" in countLines!\n\n", file);
		return(0);
		}
	i=0;
	while( fgets( line, sizeof line, ifp) != NULL)
	{
		ind=0;j=0;
		// Skip white space before first column
		while( (c=line[ind]) == ' ' & c != '\0' & c != '\n')
			ind++;
				
		while( getWord( line+ind, word, &Nchar) )
		{
	//		printf("%d %d %s\n", i,j,word);
			ind+= Nchar;
			mat[i][j] = atof(word);
			j++; // Count number of words
		}
		i++;
	}
	fclose(ifp);
	return(1);
}
int readMatrix_short(char *file, short **mat, int Nlines, int Ncols)
{
	int		i,j,ind, Nchar;
	char 	word[MAX_STR_L], line[MAX_LINE_WIDTH];
	FILE 	*ifp;
	
	if( (ifp = fopen(file, "r")) == NULL){
		printf("\nERROR: Failed to open file \"%s\" in countLines!\n\n", file);
		return(0);
		}
	i=0;
	while( fgets( line, sizeof line, ifp) != NULL)
	{
		ind=0;j=0;
		while( getWord( line+ind, word, &Nchar) )
		{
			ind+= Nchar;
			mat[i][j] = atof(word);
			j++; // Count number of words
		}
		i++;
	}
	fclose(ifp);
	return(1);
}
int readMatrix_int(char *file, int **mat, int Nlines, int Ncols)
{
	int		i,j,ind, Nchar;
	char 	word[MAX_STR_L], line[MAX_LINE_WIDTH];
	FILE 	*ifp;
	
	if( (ifp = fopen(file, "r")) == NULL){
		printf("\nERROR: Failed to open file \"%s\" in countLines!\n\n", file);
		return(0);
		}
	i=0;
	while( fgets( line, sizeof line, ifp) != NULL)
	{
		ind=0;j=0;
		while( getWord( line+ind, word, &Nchar) )
		{
			ind+= Nchar;
			mat[i][j] = atoi(word);
			j++; // Count number of words
		}
		i++;
	}
	fclose(ifp);
	return(1);
}
